version: "3.7"
services:

  mongo_db:
      image: mongo
      container_name: "mongo_db"
      ports:
        - "27017:27017"

  redis_db:
    image: redis:latest
    container_name: "redis_db"
    ports:
      - "6377:6379"


  mongo_db_test:
      image: mongo
      container_name: "mongo_db_test"
      ports:
        - "27018:27017"

  redis_db_test:
    image: redis:latest
    container_name: "redis_db_test"
    ports:
      - "6378:6379"

